# 스무딩하니, 샤프하니

# 이미지자료 분석 

# 브로드캐스팅 

# 확률변수 

`-` 베르누이분포의 합 

`-` 지수분포의 합

`-` 

In [2]:
import numpy as np

In [9]:
arr = np.array([[8,1], [4,3], [5,2]])
arr

array([[8, 1],
       [4, 3],
       [5, 2]])

In [10]:
np.apply_along_axis(func1d=np.sum,axis=1,arr=arr)

array([9, 7, 7])

In [11]:
np.apply_along_axis(func1d=lambda x: x+1,axis=1,arr=arr)

array([[9, 2],
       [5, 4],
       [6, 3]])